version: '3'

services:

  phpfpm:
    container_name: bsm-php
    image: bsm-php
    build:
      context: ./docker-files/dev/php
    env_file:
      - .env.local
    depends_on:
      - postgres
    volumes:
      - .:/app

  composer:
    container_name: bsm-composer
    image: bsm-composer
    build:
      context: ./docker-files/dev/composer
    env_file:
      - .env.local
    depends_on:
      - phpfpm
    volumes:
      - .:/app

  nginx:
    container_name: bsm-nginx
    image: bsm-nginx
    build:
      context: docker-files/dev/nginx
    env_file:
      - .env.local
    ports:
      - 80:80
    depends_on:
      - phpfpm
    volumes:
      - .:/app
      - ./logs/nginx:/var/log/nginx
      - ./docker-files/dev/nginx/default.conf:/etc/nginx/conf.d/default.conf

  postgres:
    container_name: bsm-postgres
    image: bsm-postgres
    build:
      context: docker-files/dev/postgres
    env_file:
      - .env.local
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/pgdata
    environment:
      POSTGRES_DB: asterisk
      POSTGRES_USER: upostgres
      POSTGRES_PASSWORD: 123QWErty
      PGDATA: /pgdata
